### ISSUE TITLE
Doesnt Start Emoji Chooser

### ISSUE THREAD

**Issue by hipstersmoothie** [welcoMattic/gitmoji-commit-hook#3]
when i try to commit no message is shown. When i try to --init, nothing is shown as well.

**Comment by welcoMattic** [comment]
Hi! Which version do you use?

**Comment by welcoMattic** [comment]
@hipstersmoothie 2.0.0 is published to npm, it will works now

**Comment by hipstersmoothie** [comment]
can confirm that it now works as expected
